name: Code Suggestions Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  suggest_code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Call Code Suggestions API
      id: code_suggestions
      run: |
        response=$(curl -X GET -H "Content-Type: application/json" -d '{"code": "${{ github.event.pull_request.head.sha }}"}' https://official-joke-api.appspot.com/random_joke)
        echo "$response" | jq '.' > suggestions.json
        echo "::set-output name=suggestions::$(cat suggestions.json)"

    - name: Post Code Review Suggestions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        suggestions=$(<suggestions.json)
        pr_number=${{ github.event.pull_request.number }}
        repo=${{ github.repository }}
        comments=$(echo "$suggestions" | jq -c '[.suggestions[] | {path: .file, position: .line, body: .text}]')
        review_body="### Code Review Suggestions"
        data=$(jq -n --arg event "COMMENT" --arg body "$review_body" --argjson comments "$comments" '{event: $event, body: $body, comments: $comments}')
        curl -s -H "Authorization: token $GITHUB_TOKEN" -X POST -d "$data" "https://api.github.com/repos/$repo/pulls/$pr_number/reviews"
